### ISSUE TITLE
t-stat is not updated when S_2 is modified

### ISSUE THREAD

**Issue by AntoineSoetewey** [vdecafe/inferencia#1]
Dear @vdecafe,

It seems that there is a small bug in the code for the t-test with 2 independent samples with unknown and unequal population variances.

As you can see from the screenshots below, when I modify S_2, the value of the test statistic is not updated (and thus the p-value neither):

![Screenshot 2023-11-07 at 15 54 46](https://github.com/vdecafe/inferencia/assets/17910063/49a76782-3295-4cb2-bf5c-a26bff3deae5)
![Screenshot 2023-11-07 at 15 56 03](https://github.com/vdecafe/inferencia/assets/17910063/4da3ae24-b148-4476-9bf1-21f2056f45d4)

Am I missing something?

I have not tried the other tests, so I don't know if this bug is present somewhere else or not.

Regards,
Antoine

**Comment by vdecafe** [comment]
Dear @AntoineSoetewey 

First of all thank you for notifying me of the bug.

I have reviewed the code and fixed the small error. It should work correctly now. 

Please don't hesitate to notify me of any other bugs.

Regards, 
Alejandro.

**Comment by AntoineSoetewey** [comment]
Great!
